---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-example
  name: service-example-deployment
  namespace: clase2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-example
  template:
    metadata:
      labels:
        app: service-example
    spec:
      containers:
        - env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: ovhplatform/what-is-my-pod:1.0.1
          imagePullPolicy: IfNotPresent
          name: service-example
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: '100Mi'
              cpu: 10m
            limits:
              memory: '200Mi'
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-example
  name: service-example
  namespace: clase2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-example
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-example
  name: service-example-nodeport
  namespace: clase2
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30007
  selector:
    app: service-example
